# Generated by Django 4.2.7 on 2023-11-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todosite", "0002_remove_userprofile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="todogroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="newtodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_todo", models.CharField(max_length=30)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todosite.todogroup",
                    ),
                ),
            ],
        ),
    ]
